### ISSUE TITLE
Bug : related to UA

### ISSUE THREAD

**Issue by TH3xACE** [Tw1sm/badger-builder#2]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/tools/badger-builder/badger_builder/__init__.py", line 1, in <module>
    from badger_builder.__main__ import app # noqa
  File "/opt/tools/badger-builder/badger_builder/__main__.py", line 2, in <module>
    from badger_builder.commands import __all__
  File "/opt/tools/badger-builder/badger_builder/commands/__init__.py", line 1, in <module>
    from badger_builder.commands import create, parse
  File "/opt/tools/badger-builder/badger_builder/commands/create.py", line 10, in <module>
    from badger_builder.lib.configs.listener import UserAgent, DataFormat, ObfSleep, get_ua_string
  File "/opt/tools/badger-builder/badger_builder/lib/configs/listener/__init__.py", line 1, in <module>
    from badger_builder.lib.configs.listener.useragent import UserAgent, get_ua_string # noqa: F401
  File "/opt/tools/badger-builder/badger_builder/lib/configs/listener/useragent.py", line 16
    match ua:
          ^
SyntaxError: invalid syntax

**Comment by Tw1sm** [comment]
You need to upgrade to Python3.10 or later
